import { SignInButton, SignOutButton } from "@clerk/nextjs";
import Head from "next/head";
import { CreatePost } from "~/components/create-post";
import { Posts } from "~/components/posts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center justify-between border-x border-y p-4 ">
        <CreatePost />

        {/* <SignOutButton>
              <div className=" cursor-pointer text-cyan-50">
                Sign out
              </div>
            </SignOutButton>
            <SignInButton>
              <div className=" cursor-pointer text-cyan-50">
                Sign in
              </div>
            </SignInButton> */}
      </div>
      <Posts />
    </>
  );
}
